language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t shasankasekhar/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true shasankasekhar/react-test npm run test

after_success:
  - docker build -t shasankasekhar/multi-client ./client
  - docker build -t shasankasekhar/multi-nginx ./nginx
  - docker build -t shasankasekhar/multi-server ./server
  - docker build -t shasankasekhar/multi-worker ./worker
  #Doing dcoker login
  - echo "$Docker_password"|docker login -u "$Docker_user" --password-stdin
  - docker push shasankasekhar/multi-client
  - docker push shasankasekhar/multi-nginx
  - docker push shasankasekhar/multi-server
  - docker push shasankasekhar/multi-worker


   

